### ISSUE TITLE
UI test for update role and permissions

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-accounts#105]
Since now we can update the roles of the user after logging in as admin user we need UI tests for that. 
Also, non-admin users should not be able to see the accounts list.

**Comment by kulmann** [comment]
With this https://github.com/owncloud/ocis-accounts/pull/100 (already merged) accounts can only be listed as admin user. There are plans to hide the accounts app entirely if the logged in user doesn't have account management permissions.

There is one UI test for assigning a role. If you have ideas for more, please describe your plans in a ticket :-) 👍
