### ISSUE TITLE
Add error information to responses

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis-accounts#11]
Currently an rpc-get call results in a 500 internal server error if a key does not exist. It is impossible from a caller perspective to distinguish between not found and real failures.

Proposal:
- Refactor the protobuf definition like described [here](https://hackernoon.com/handling-errors-in-golang-grpc-and-go-kit-services-d0fa0a112449 ) i.e wrap results in to XXXResponse envelopes which contain an additional error struct.

- Instead directly exposing the generated client write a wrapper which transparently unpacks the above envelope and does transparent error-handling? Tough not sure if this would be compatible with micro? Maybe this can be achieved differently?

**Comment by refs** [comment]
I rather go with the "return nothing" approach [here](https://github.com/owncloud/ocis-accounts/commit/1324b9fd1f61cfaa0d0b9060d0de9bc68da49c7b). WDYT?

**Comment by IljaN** [comment]
> I rather go with the "return nothing" approach here. WDYT?
Yes this would work.

Yes would be possible. But wouldn't this break the if err !=nil pattern at the consumer thus requiring to check for empty Record?

**Comment by refs** [comment]
We had a deeper look @butonic and I this morning and found a few things we need to tackle. The first and most crucial one [is this](https://github.com/owncloud/ocis-pkg/issues/38).

Then there's the issue of whether we should enforce using go-micro clients to handle requests between services vs using the [grpc go client](https://github.com/grpc/grpc-go), which, this needs TBC, go-micro allows to via setting an environment variable.

If we have to set it on stone I would settle for `go-micro` client.

**Comment by butonic** [comment]
This came up again. And we should use the [go-micro errors package](https://github.com/micro/go-micro/tree/master/errors), which allows adding error detauls to the error in a similar way that [google developed it](https://cloud.google.com/apis/design/errors#error_model), which is the official recommendation aka [gRPC Richer Error Model](https://grpc.io/docs/guides/error/#richer-error-model)

cc @C0rby
