### ISSUE TITLE
Disabled account can still log in

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/ocis-accounts#113]
When a user is disabled via WebUI, he can still log in. Checking the file of the user, the key `accountEnabled` is gone when it's set to false. Not sure if this is a bug in the WebUI or backend.

**Comment by kulmann** [comment]
Looks like it's correct that the key vanishes from the file when set to `false`.

**Comment by kulmann** [comment]
Did you try restarting the service after setting the it to `false`? Maybe it's a bug with keeping the in memory data up to date.

**Comment by kulmann** [comment]
Restarting the service (or entire ocis bundle) will reload the data from disk.

**Comment by LukasHirt** [comment]
> Did you try restarting the service after setting the it to false? Maybe it's a bug with keeping the in memory data up to date.

Yep, restart helped.

**Comment by kulmann** [comment]
I will fix the in memory update then 👍

**Comment by kulmann** [comment]
In memory update of the index works fine. I identified the issue in ocis-proxy: we have an account cache there - which makes sense. But it doesn't get updated when the account is updated. Need to invalidate the cached account or kill the cache entirely.
