### ISSUE TITLE
bleve index still case sensitive

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-accounts#128]
master branch is broken as the moment of this writing (9f6355a96875e98f0bf518cb96db07203e29e4cf)

## Steps to reproduce:
- Start ocis server
- Create a user using the provisioning API `curl -X POST http://localhost:9110/ocs/v1.php/cloud/users -d userid=michael -d password="spaces in my password" -d username="michael" -d displayname="display name" -d email="michael@email.com" -d enabled="true" | xmllint --format -`
- Delete the user using a case sensitive ID `curl -X DELETE http://localhost:9110/ocs/v1.php/cloud/users/MiChAEl`
- Create the user again using the Command from step 2

### Expected

- no error

### Actual

- `2020-09-22T14:48:50+02:00 ERR could not add user error="{\"id\":\"com.owncloud.api.accounts\",\"code\":400,\"detail\":\"account already exists\",\"status\":\"Bad Request\"}" service=ocs userid=michael`

Latest working commit is (e55b8ae2f440e20e657fdc21827b935f64bd8458)

**Comment by kulmann** [comment]
Related to this: https://github.com/owncloud/ocis-ocs/issues/64

**Comment by kulmann** [comment]
The new index implementation, with the changes to OCS that we made, is behaving correct for this.

Response on the second create request:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <enabled>true</enabled>
    <id>michael</id>
    <display-name>display name</display-name>
    <displayname>display name</displayname>
    <email>michael@email.com</email>
    <uidnumber>20005</uidnumber>
    <gidnumber>30000</gidnumber>
  </data>
</ocs>
```
