### ISSUE TITLE
Discussion: Account Files Format

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-accounts#2]
The current implementation uses a very simple definition with some basic user data. We've seen proposals from @butonic like [systemd's user records](https://github.com/poettering/systemd/blob/homed/docs/USER_RECORD.md) but ultimately we have to come up with a solution that fits for us.

For this let's use this document to try and come with a standard way of dealing with this.

Related draft for ocis-proxy: https://github.com/owncloud/ocis-proxy/issues/35

**Comment by butonic** [comment]
The layout on disk needs to support efficient lookup for the possible API calls.

While the current API supports a key based query (by uuid), the most frequent call will happen when sub@iss or email is exchanged for the uuid after authenticating a user with openid connect. 

- [ ] The API query message will need to be extended with sub iss and email. 
- [ ] The layout on disk can create symbolic links or even hard links to the uuid named accounts:
  /uuid/1-2-3-4
  /issuer/domain.tld:port/random-sub
  /email/foo@domain.tld
  Can all point to the same filenode.

- [ ] The lookups can be cached and invalidated if the mtime changes.

**Comment by butonic** [comment]
accounts will be stored using the ldap protocol. ocis-glauth as a drop in replacement is working on homedir based users.
