### ISSUE TITLE
Rename SettingsService to AccountService

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-accounts#27]
here: https://github.com/owncloud/ocis-accounts/blob/master/pkg/proto/v0/accounts.proto#L7

- Run `protoc`

**Comment by kulmann** [comment]
I just wanted to write an issue about this, because there was a bit of confusion about the naming of this service in the deployment workshop. Nice that you already have it. So 👍 for doing this soon to reduce potential for misunderstanding.

**Comment by karakayasemi** [comment]
As far as I understand from this comment https://github.com/owncloud/ocis-accounts/pull/28#issuecomment-624743455, this one is resolved with #28.

@refs Just wanted to remind, since the master branch is constantly changing, using permalink can be beneficial when pointing a code line. Thanks.
