### ISSUE TITLE
write GRPC tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-accounts#29]
see example https://github.com/owncloud/ocis-hello/blob/master/pkg/proto/v0/hello.pb.micro_test.go

**Comment by dpakach** [comment]
Looks like https://github.com/owncloud/ocis-accounts/pull/30 changes a lot of APIs so waiting for that to get merged before proceeding with it.

**Comment by dpakach** [comment]
[ ] - Test for updating accout
