### ISSUE TITLE
Error not returned in bad gRPC requests

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-accounts#62]
Some gRPC calls dont return proper error when it is expected

- [ ] - RemoveMember - removing member that is not in the group doesn't return any error
- [x] - CreateAccount - Try to create a user that already exists
- [ ] - AddMember - Try to add a user that is already in the group

**Comment by kulmann** [comment]
Fixed that `CreateAccount` now doesn't create duplicate accounts anymore. https://github.com/owncloud/ocis-accounts/pull/123
