### ISSUE TITLE
Too many open fd

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-accounts#79]
Hitting a limit of open fd:

![image](https://user-images.githubusercontent.com/6905948/89286521-a8731c80-d652-11ea-8c32-294ec7525cfb.png)

**Comment by refs** [comment]
each run adds the same delta to the list of open files: ∆=14

**Comment by refs** [comment]
test being run:

```
make test-acceptance-api \
TEST_SERVER_URL=https://localhost:9200 \
TEST_OCIS=true \
OCIS_REVA_DATA_ROOT=/var/tmp/reva/ \
SKELETON_DIR=apps/testing/data/apiSkeleton \
BEHAT_FEATURE=tests/acceptance/features/apiShareManagementBasic/createShare.feature:88
```

**Comment by refs** [comment]
delta command: `ls -p [accounts-pid] | wc -l`

**Comment by PVince81** [comment]
as discovered, it's network connections that are left open between ocis-accounts and ocis-ocs after updating an account

**Comment by PVince81** [comment]
fix is here: https://github.com/owncloud/ocis-ocs/pull/29

**Comment by individual-it** [comment]
looks similar to https://github.com/owncloud/ocis/issues/268

**Comment by PVince81** [comment]
I think this was brand new code
