### ISSUE TITLE
account deletion shoud be possible case insensitive

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-accounts#81]
test using ocis single binary in https://github.com/owncloud/ocis/pull/409

1. create user `curl -k -X POST https://localhost:9200/ocs/v1.php/cloud/users    -d userid="Phil"    -d password="phil" -d email="phil@a.de" -d username="Phil"`
2. delete user using different case: `curl -k -X DELETE https://localhost:9200/ocs/v1.php/cloud/users/phil`
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>998</statuscode><message>The requested user could not be found</message></meta></ocs>
```

**Comment by kulmann** [comment]
Fixed with https://github.com/owncloud/ocis/pull/709
